### ISSUE TITLE
rack 3.0 support

### ISSUE THREAD

**Issue by metapsj** [jaredmdobson/rack-livereload#11]
will rack-livereload support rack 3.0?

here some of the changes that effect rack-livereload.

- Response header keys can no longer include uppercase characters.
- Rack::Headers added to support lower-case header keys.

i've included links to rack 3.0's change log and upgrade guide as a convenience.

change log
https://github.com/rack/rack/blob/3.0.0/CHANGELOG.md

upgrade guide
https://github.com/rack/rack/blob/3.0.0/UPGRADE-GUIDE.md

**Comment by jaredmdobson** [comment]
Thanks for looking at this

**Comment by Kulgar** [comment]
That would be quite a task to do, wouldn't it? But yeah, that would be a nice to have. Although I'm not sure if that would bring breaking changes or not. 

Feel free to help us on that @metapsj  :-)

**Comment by Fjan** [comment]
The rack-live reload works fine with Rack 3 in my testing, if I use gem version 0.5.1. Confusingly, if I understand correctly, the patch for it is in 0.5.1, it is _not_ in 0.5.2, but it looks like it has been re-applied in the (unreleased) 0.6.0. There was a flurry of activity 2 months ago, but version 0.6.0 is still unreleased. @jaredmdobson is my understanding correct?

**Comment by jaredmdobson** [comment]
@Fjan i'm looking for a new maintainer, i'm not sure if @Kulgar released any versions?

**Comment by Kulgar** [comment]
Hello - unfortunately no, I am really really busy - I hardly find the time to update the open source projects that I have access to. I do update some, sometimes... 

But I would certainly have time to review a pull request and make a new release :-)

**Comment by Fjan** [comment]
@Kulgar I _think_ the current version in master can just be released, the only thing that was changed is the gemspec to lock it to rack 3, and the version number was updated, and that's all that needed to happen

**Comment by jaredmdobson** [comment]
I understand @Kulgar :).   i believe @Fjan if that's something you can do?

I have yet been able to get master to work on my machine.  @Fjan if you get it working on your local code and want to push a new version i can give you permission.  Also i would look into the gem "hotwire-livereload" as that's what i use.

**Comment by Kulgar** [comment]
@jaredmdobson : ow! I didn't know about hotwire-livereload, thanks for that info! I was still using guard-livereload... which isn't maintained since ages... but I'm guessing that to use hotwire-livereload you need to actually be using the hotwire stack. I don't use that on all my projects yet. 

How would you test hotwire-livereload + rack-livereload master code? By just starting a new rails 7 app that is actually using both gems? 

I could at least give that a try. 

You're saying that you weren't able to get master to work on your machine, did you get any errors to share?

**Comment by jaredmdobson** [comment]
I'm not sure if hotwire-livereload works at all with rack-livereload.  

Yeah the errors come from using out of date libraries and ruby versions, if you checkout the repo code and get it to bundle and install and run, i can give you access to publish the gem you're looking for.

Best of luck :)

**Comment by Fjan** [comment]
> I have yet been able to get master to work on my machine

@jaredmdobson It's odd that it doesn't work for you, the current master is pretty much the same as the old version 0.5.1. It just has rack 3 added as a constraint to the gem spec and the version bumped to 0.6.0. It works fine for me, as it should  because it's basically the same as 0.5.1, but it would be nice to get a new release to prevent bundler showing it as outdated. That's just my OCD I guess 🙂, but an outdated version number showing is not important enough to go through the hassle to assume a maintainer role just to click "release".

**Comment by Kulgar** [comment]
@jaredmdobson : well... I've used ruby 3.1.4, did a bundle install, and ran rspec... 
I have rack 3.0.10 installed in my Gemfile.lock... And... 

![image](https://github.com/jaredmdobson/rack-livereload/assets/856044/6ff89763-6c2a-41ac-8bfc-de022acac68f)

Look at that, it totally works without any changes. 

Ruby is really magical, teehee :-)

I'm just happy that everything seem to work "just like that". 

So... I'm guessing, we could do a new release for 0.6.0? What do you think? 

Should I test the gem in a real project?

**Comment by Fjan** [comment]
I tried the master branch in a nanoc project, and it worked fine. So with that and the green tests it should be good to go, right?

**Comment by Kulgar** [comment]
Indeed it should. 
I'll gladly do a new release - it seems that I already have access to the gem on rubygems (totally forgot that I did ^^'). 

So just waiting for @jaredmdobson thoughts. And if he's ok, then, let's release the new version! :-)

**Comment by jaredmdobson** [comment]
Yes please, thank you 😊

**Comment by Kulgar** [comment]
@jaredmdobson @Fjan : and done - https://rubygems.org/gems/rack-livereload :-)

**Comment by Fjan** [comment]
Great! I think this issue can be closed.

**Comment by Kulgar** [comment]
Sure, thanks for your help @Fjan :-)

**Comment by jaredmdobson** [comment]
Thank you @Fjan 👍🏿 🎉
